spring:
  datasource:
    url: jdbc:mysql://localhost:3306/apparel
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

services:
  auth-service-url: http://localhost:8080



